apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-conf
data:
  env: |
    MONGO_DSN=mongodb://root:root@mongodb/nest?authSource=admin
    KAFKA_CLIENT_ID=code-delivery
    KAFKA_BROKER=host.kafka:9092
    KAFKA_CONSUMER_GROUP_ID=code-delivery
    KAFKA_SASL_USERNAME=USER_KAFKA
    KAFKA_SASL_PASSWORD=PASSWORD_KAFKA
